### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by IzzySoft** [OldSparkyMI/aRevelation#1]
If possible, a license should explicitly stated for this project. Being a fork, this might need to be addressed "upstream" at least for the original code by @MarmaladeSky

**Comment by IzzySoft** [comment]
Still undecided – or is the problem "upstream"?

**Comment by IzzySoft** [comment]
Bumping this again. With the original project "in hibernation", I'd very much like to see this one in the official F-Droid repo (don't get me wrong: I gladly have it in mine, but it's better found when there) – which cannot be done without a (FOSS) license.

**Comment by OldSparkyMI** [comment]
close #1

**Comment by IzzySoft** [comment]
Cool, thanks! So what do you think about bringing this to the official F-Droid repo now? Oh: and thanks for the thanks section :smiley:

**Comment by OldSparkyMI** [comment]
I never lost a thought about this. It is in the official play store. I will keep it in mind.

**Comment by IzzySoft** [comment]
What, in the toys shop? Sparky, an app focussed on privacy and security belongs to F-Droid – where folks focused on privacy and security get their apps. Luckily I have yours in my repo, or else; my device is completely free of GApps (arrived, unpacked, unlocked, TWRP + LOS :smile:).

So if you're OK with it, I'll do the job for you. Disclosure: I'm one of the F-Droid maintainers meanwhile :innocent: Just give me your go, and I go for it.

**Comment by IzzySoft** [comment]
Thanks for your mail! I've [opened an RFP](https://gitlab.com/fdroid/rfp/issues/772) (Request For Packaging) with F-Droid; you might wish to cross-check the details I've entered to make sure they meet your wishes.

If no problems come up (I don't suspect any), there's nothing more for you to do – except for publishing a release every now and then, and tagging it accordingly :wink:

If you wish for screenshots being used in the F-Droid client and on the F-Droid website, you can maintain them in your repo here via Fastlane/Triple-T (see e.g. [here](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-apps-source-repository) for details). That way you have full control over them. If you wish, you can do the same for summary and description (in that case just let me know to update metadata).

That OK with you?

**Comment by IzzySoft** [comment]
OK, our bot accepted it. Just for reference: it [found an "insecure gradlew"](https://gitlab.com/fdroid/rfp/issues/772#note_112612033) you might wish to fix.
