### ISSUE TITLE
Typo in the Fdroid Description

### ISSUE THREAD

**Issue by Ivan64** [OldSparkyMI/aRevelation#15]
It is claimed that it is a fork of the no longer maintained "aRevelation"

**Comment by OldSparkyMI** [comment]
Thanks for your report, but I don't know what you like to say.
aRevelation is a fork of aRevelation from https://github.com/sviro/aRevelation and this repository is no longer under maintenance.
Neither my English is bad or I don't find any typo in the F-Droid description for aRevelation.

Could you please be a little more precise?

**Comment by Ivan64** [comment]
My mistake. I thought it was forked from Revelation.

**Comment by OldSparkyMI** [comment]
No problem, thanks for you report and have a nice day!
