### ISSUE TITLE
Some files created by Linux Reveleation cannot be opened due to XML error

### ISSUE THREAD

**Issue by rudolphi** [OldSparkyMI/aRevelation#16]
![photo_2019-06-03_19-51-55](https://user-images.githubusercontent.com/13907452/58823099-357aaa00-8639-11e9-8c5a-f26421318182.jpg)

**Comment by OldSparkyMI** [comment]
I will fix this issue in a week or two - sry.

**Comment by OldSparkyMI** [comment]
Fixed in 1.10.
