### ISSUE TITLE
Re-Lock database when application was left

### ISSUE THREAD

**Issue by IzzySoft** [OldSparkyMI/aRevelation#3]
The database isn't locked when

* one switches off the screen and then back on again
* one switches to a different app and then back again

That's a security risk. While some users might like this (faster access), others might find this dangerous. The original version asked to input the passphrase again in both cases. Maybe make that an option (as soon as there's a preferences dialog, that is)?

**Comment by OldSparkyMI** [comment]
Wish granted in version 1.0RC1

**Comment by IzzySoft** [comment]
Yay! \o/
