### ISSUE TITLE
Option to have password "initially visible"

### ISSUE THREAD

**Issue by IzzySoft** [OldSparkyMI/aRevelation#4]
Speaking about options: 1.0b1 (as well as 0.1) had the password directly visible when having opened a record (might be due to the fact that was my setting in the desktop app when having saved the safe). With 1.0b2 one must explicitly tap the field, and later close the popup.

Like with the desktop app, it would be nice to have an option to make the password "initially visible". Another nice idea would be an "eye icon" next to it to toggle visibility.

Btw: with that popup, is the entry already editable, and would the change be saved back? I've also noticed the FAB for new entries – but no "edit" in the 3-dots-overflow menu, so I was wondering about edit functionality in general (especially as the changelog doesn't mention that, though with c1458c2 there seems to be a related commit).

**Comment by OldSparkyMI** [comment]
> is the entry already editable

Yes, you can edit the password and other secrets.

> and would the change be saved back

Only if you click the "save button" afterwards.

> I've also noticed the FAB for new entries

Yes, you can add new entries.

> but no "edit" in the 3-dots-overflow menu

Yes, edit mode is enabled by default.

> changelog doesn't mention that

Yes, sorry for that.

**Comment by OldSparkyMI** [comment]
Wish granted in version 1.0RC1

**Comment by IzzySoft** [comment]
Wow! Need to run my updater! Yuck, my updater doesn't recognise it as update as 1.0X1 is smaller than 1.0X3 … *kicking it* There, now it comes (manually pulled … check triggered … rebuild+sync triggered).

Will check as soon as I find time, thanks a lot! You've been quite busy :wink: :+1:
