### ISSUE TITLE
toast displays over other apps when aRevelation is in background

### ISSUE THREAD

**Issue by IzzySoft** [OldSparkyMI/aRevelation#7]
Even with aRevelation in background, when I unlock the screen having some other app in foreground I sometimes see a toast display telling me it will lock the database in X seconds. That's unexpected for several reasons:

* automatically lock if app in background is set to "immediately" (no delay), so there should be no count-down at all in described situation
* lock automatically after has no time selected at all (I've set that to 15min now)
* screen was even locked in between (missing setting: "lock database when screen is turned off")

Could you please check and fix that, plus include that third option (default should be to lock immediately when screen is being turned off; this can be a simple "yes/no" or, if you like, a range of times like with the second option)?

**Comment by OldSparkyMI** [comment]
1.2 is likely to be released on Sunday, 2018-01-14.

**Comment by IzzySoft** [comment]
Cool, thanks! Will notice when it pops up in my repo :wink:
